In [2]:
# version確認
import torch
print(torch.__version__)
print(f'cuda = {torch.cuda.is_available()}')

2.1.0+cu121
cuda = True


In [11]:
# create some experimental tensor

x_s = torch.empty(1)
print(x_s)
x_v = torch.empty(2) # 2 and more
print(x_v)
x_m = torch.empty(2,3) # 2 times 3 element vector
print(x_m)
x_mm = torch.empty(2,3,4) # 2 times 3x4 matrix, 2 times ( 3 times 4 element vector)
print(x_mm)

tensor([-5.9474e+28])
tensor([-1.6908e+00,  4.3164e-41])
tensor([[-6.0448e+28,  3.2541e-41, -5.9619e+28],
        [ 3.2541e-41,         nan,         nan]])
tensor([[[-5.9582e+28,  3.2541e-41, -5.9471e+28,  3.2541e-41],
         [ 8.9683e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [ 6.8708e+02,  3.2537e-41,  1.5766e-19,  1.4585e-19]],

        [[ 7.1856e+22,  1.8609e+34,  1.8179e+31,  1.8524e+28],
         [ 1.5766e-19,  1.4610e-19,  7.3159e+34,  1.6634e+22],
         [ 4.5100e+16,  4.4972e-41,  1.3593e-43,  0.0000e+00]]])


In [13]:
# random matrix, vecor creation with tensor
rand_m = torch.rand(5,3) # 5 times 3 element vector
print(rand_m)

zero_v = torch.zeros(5,3) # and torch.ones(xxx)
print(zero_v)


tensor([[0.9206, 0.3227, 0.2499],
        [0.5306, 0.4537, 0.6692],
        [0.1897, 0.7861, 0.2111],
        [0.2391, 0.0385, 0.2829],
        [0.6435, 0.6727, 0.0656]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
# there is size and dimention feature for getting information about tensor attributes
import torch

rand_m = torch.rand(2,6)
ones_mm = torch.ones(4,2,3)

print(f'size of vector: {rand_m.size()}')
print(f'dim of mm: {ones_mm.shape}') # this shape also use with cv2 frames (like 1080 1920 3 return value)

size of vector: torch.Size([2, 6])
dim of mm: torch.Size([4, 2, 3])
