In [ ]:
# version確認
import torch
print(torch.__version__)
print(f'cuda = {torch.cuda.is_available()}')

2.1.0+cu121
cuda = True


In [ ]:
# create some experimental tensor

x_s = torch.empty(1)
print(x_s)
x_v = torch.empty(2) # 2 and more
print(x_v)
x_m = torch.empty(2,3) # 2 times 3 element vector
print(x_m)
x_mm = torch.empty(2,3,4) # 2 times 3x4 matrix, 2 times ( 3 times 4 element vector)
print(x_mm)

tensor([-5.9474e+28])
tensor([-1.6908e+00,  4.3164e-41])
tensor([[-6.0448e+28,  3.2541e-41, -5.9619e+28],
        [ 3.2541e-41,         nan,         nan]])
tensor([[[-5.9582e+28,  3.2541e-41, -5.9471e+28,  3.2541e-41],
         [ 8.9683e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [ 6.8708e+02,  3.2537e-41,  1.5766e-19,  1.4585e-19]],

        [[ 7.1856e+22,  1.8609e+34,  1.8179e+31,  1.8524e+28],
         [ 1.5766e-19,  1.4610e-19,  7.3159e+34,  1.6634e+22],
         [ 4.5100e+16,  4.4972e-41,  1.3593e-43,  0.0000e+00]]])


In [ ]:
# random matrix, vecor creation with tensor
rand_m = torch.rand(5,3) # 5 times 3 element vector
print(rand_m)

zero_v = torch.zeros(5,3) # and torch.ones(xxx)
print(zero_v)


tensor([[0.4740, 0.6766, 0.6660],
        [0.4335, 0.9273, 0.4065],
        [0.7552, 0.0750, 0.8497],
        [0.8156, 0.1008, 0.2147],
        [0.9143, 0.5890, 0.2020]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
# there is size and dimention feature for getting information about tensor attributes
import torch

rand_m = torch.rand(2,6)
ones_mm = torch.ones(4,2,3)

print(f'size of vector: {rand_m.size()}')
print(f'dim of mm: {ones_mm.shape}') # this shape also use with cv2 frames (like 1080 1920 3 return value)

# checkout the data types -> tensor as default set to <torch.float32>
print(rand_m.dtype)

# if you want to change data type for your tensor, can define with parameeters
ones_v_d16 = torch.ones(2,5, dtype=torch.float16)
print(f'set f16 data type: {ones_v_d16.dtype}')

# also when print new dtype tensor, shows its features
print(ones_v_d16)



size of vector: torch.Size([2, 6])
dim of mm: torch.Size([4, 2, 3])
torch.float32
set f16 data type: torch.float16
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float16)


In [ ]:
# data saving in the momory
import torch
import numpy

a = numpy.ones(5)
# print(a)

b = torch.from_numpy(a)
c = torch.tensor(a)

a +=1
print(a)
print(b) #as seen, b not copied, just share same referance
print(c)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
import torch

dev = 'cuda' if torch.cuda.is_available() else 'cpu'
device = torch.device(dev)

print(device)

# here, define tensor on GPU for faster process
x = torch.rand(5,3).to(device)
print(x) #device CUDA

# the small optimization, directly created on GPU. Not created on CPU to move to GPU like above
x_otherway = torch.rand(5,3, device=dev)
print(f'\n{x_otherway}')



cpu
tensor([[0.8120, 0.3899, 0.9117],
        [0.9053, 0.7682, 0.2854],
        [0.7619, 0.1997, 0.4505],
        [0.8914, 0.5881, 0.9842],
        [0.1111, 0.9941, 0.7202]])

tensor([[0.9059, 0.7016, 0.0740],
        [0.4976, 0.1850, 0.8933],
        [0.1836, 0.7645, 0.9476],
        [0.2285, 0.4386, 0.1087],
        [0.6299, 0.0541, 0.8538]])
